---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prometheus-operator
  namespace: ml-workshop

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prometheus-k8s
  namespace: ml-workshop

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-role
  namespace: ml-workshop

subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: ml-workshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s-role
  namespace: ml-workshop

subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: ml-workshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin